#  Copyright (c) 2022 Bosch Rexroth AG
#  All rights reserved. See LICENSE file for details.
name: can-demo # Name of resulting snap.
base: core18
version: '0.1.0'
summary: This is a sample CAN snap.
description: |
  This is a sample CAN snap written with Go.

architectures:      
  - build-on: amd64
    run-on: armhf

grade: devel
confinement: strict # Strict confines the snap's access to only its sandbox.

apps:
  run:
    command: bin/can-demo # Declares command to be run on start up.
    daemon: simple # Specifies the snap should be started on boot up.
    plugs: [ network ] # Grants access to network devices like can.
    restart-condition: always # On failure the snap is restarted.

parts:
  res:
    plugin: dump # Pack files into snap.
    source: .
    prime:
      - 'COPYRIGHT'
      - 'LICENSE'
      - 'bin/can-demo'
